"""added 2 weeks playtime column to usergame table

Revision ID: 00acb769f55a
Revises: ef866126d82e
Create Date: 2026-09-21 07:43:57.906925

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "00acb769f55a"
down_revision: str | Sequence[str] | None = "ef866126d82e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
