"""add metadata availability

Revision ID: 9ccf2c7a475f
Revises: fee6ee92e17c
Create Date: 2026-09-18 13:04:01.035544

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ccf2c7a475f'
down_revision: str | Sequence[str] | None = 'fee6ee92e17c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('metadata_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'metadata_available')
    # ### end Alembic commands ###
