"""add user game preferences

Revision ID: 9ffca988319e
Revises: d24564f0d1fe
Create Date: 2026-09-23 08:19:51.442922

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ffca988319e'
down_revision: str | Sequence[str] | None = 'd24564f0d1fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_game_preferences',
    sa.Column('steamid64', sa.String(length=255), nullable=False),
    sa.Column('steam_app_id', sa.Integer(), nullable=False),
    sa.Column('preference', sa.String(length=20), nullable=False),
    sa.Column('preference_last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['steam_app_id'], ['games.steam_app_id'], ),
    sa.ForeignKeyConstraint(['steamid64'], ['users.steamid64'], ),
    sa.PrimaryKeyConstraint('steamid64', 'steam_app_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_preferences')
    # ### end Alembic commands ###
