"""added steam sync metadata

Revision ID: a153da770b59
Revises: 13a8a9e1c52f
Create Date: 2026-09-18 07:17:41.270285

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a153da770b59'
down_revision: str | Sequence[str] | None = '13a8a9e1c52f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('games', sa.Column('price_change_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'price_change_number')
    op.drop_column('games', 'last_modified')
    # ### end Alembic commands ###
