"""added game metadata columns

Revision ID: bfdb0d72e903
Revises: da1c93e23260
Create Date: 2026-09-18 12:12:14.233626

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bfdb0d72e903"
down_revision: str | Sequence[str] | None = "da1c93e23260"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("header_image", sa.Text(), nullable=True))
    op.add_column("games", sa.Column("review_score", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("review_score_desc", sa.Text(), nullable=True))
    op.add_column("games", sa.Column("total_positive", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("total_negative", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("total_reviews", sa.Integer(), nullable=True))
    op.add_column(
        "games",
        sa.Column("genres", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "games",
        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "games",
        sa.Column("developers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "games",
        sa.Column("publishers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_unique_constraint(None, "sync_state", ["source"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "sync_state", type_="unique")
    op.drop_column("games", "publishers")
    op.drop_column("games", "developers")
    op.drop_column("games", "categories")
    op.drop_column("games", "genres")
    op.drop_column("games", "total_reviews")
    op.drop_column("games", "total_negative")
    op.drop_column("games", "total_positive")
    op.drop_column("games", "review_score_desc")
    op.drop_column("games", "review_score")
    op.drop_column("games", "header_image")
    # ### end Alembic commands ###
