"""restore tables and add user library schema

Revision ID: d24564f0d1fe
Revises: 00acb769f55a
Create Date: 2026-09-21 08:03:41.096708

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d24564f0d1fe"
down_revision: str | Sequence[str] | None = "00acb769f55a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("steam_app_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("price_change_number", sa.Integer(), nullable=True),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("header_image", sa.Text(), nullable=True),
        sa.Column("review_score", sa.Integer(), nullable=True),
        sa.Column("review_score_desc", sa.Text(), nullable=True),
        sa.Column("total_positive", sa.Integer(), nullable=True),
        sa.Column("total_negative", sa.Integer(), nullable=True),
        sa.Column("total_reviews", sa.Integer(), nullable=True),
        sa.Column("genres", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("developers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("publishers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_available", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_name"), "games", ["name"], unique=False)
    op.create_index(
        op.f("ix_games_steam_app_id"), "games", ["steam_app_id"], unique=True
    )
    op.create_table(
        "steam_metadata_failures",
        sa.Column("steam_app_id", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_failed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("steam_app_id"),
    )
    op.create_table(
        "sync_state",
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("source"),
    )
    op.create_table(
        "users",
        sa.Column("steamid64", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("library_last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("steamid64"),
    )
    op.create_table(
        "user_games",
        sa.Column("steamid64", sa.String(length=255), nullable=False),
        sa.Column("steam_app_id", sa.Integer(), nullable=False),
        sa.Column("playtime_forever_minutes", sa.Integer(), nullable=True),
        sa.Column("playtime_2weeks_minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["steam_app_id"],
            ["games.steam_app_id"],
        ),
        sa.ForeignKeyConstraint(
            ["steamid64"],
            ["users.steamid64"],
        ),
        sa.PrimaryKeyConstraint("steamid64", "steam_app_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_games")
    op.drop_table("users")
    op.drop_table("sync_state")
    op.drop_table("steam_metadata_failures")
    op.drop_index(op.f("ix_games_steam_app_id"), table_name="games")
    op.drop_index(op.f("ix_games_name"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
