"""added sync state for info sources

Revision ID: da1c93e23260
Revises: a153da770b59
Create Date: 2026-09-18 07:32:19.316593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1c93e23260'
down_revision: Union[str, Sequence[str], None] = 'a153da770b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_state',
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('source'),
    sa.UniqueConstraint('source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    # ### end Alembic commands ###
