"""Added User and UserGame tables

Revision ID: ef866126d82e
Revises: 2bca173f1556
Create Date: 2026-09-21 07:38:37.994011

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef866126d82e'
down_revision: str | Sequence[str] | None = '2bca173f1556'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_steam_app_id'), table_name='games')
    op.drop_table('games')
    op.drop_table('steam_metadata_failures')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_metadata_failures',
    sa.Column('steam_app_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_failed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('steam_app_id', name=op.f('steam_metadata_failures_pkey'))
    )
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('steam_app_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_free', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('price_change_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('header_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_score_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_positive', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_negative', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('developers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('publishers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metadata_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('metadata_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('games_pkey'))
    )
    op.create_index(op.f('ix_games_steam_app_id'), 'games', ['steam_app_id'], unique=True)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_table('sync_state',
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('source', name=op.f('sync_state_pkey'))
    )
    # ### end Alembic commands ###
