"""organised tables in models.py

Revision ID: f070d6e856c7
Revises: e496214e7109
Create Date: 2026-09-21 04:41:55.784640

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f070d6e856c7'
down_revision: str | Sequence[str] | None = 'e496214e7109'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    op.drop_table('steam_metadata_failures')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_metadata_failures',
    sa.Column('steam_app_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_failed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('steam_app_id', name=op.f('steam_metadata_failures_pkey'))
    )
    op.create_table('sync_state',
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('source', name=op.f('sync_state_pkey')),
    sa.UniqueConstraint('source', name=op.f('sync_state_source_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
