"""added metadata sync time column for game table

Revision ID: fee6ee92e17c
Revises: bfdb0d72e903
Create Date: 2026-09-18 12:33:20.510187

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fee6ee92e17c"
down_revision: str | Sequence[str] | None = "bfdb0d72e903"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column("metadata_synced_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "metadata_synced_at")
    # ### end Alembic commands ###
